workflows:
  flutter-android:
    name: Flutter Android Build
    max_build_duration: 60
    environment:
      flutter: latest
      java: 11
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build Android (release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
